# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 은조 블로그 @pgonee
email: pgonee@gmail.com
description: >-
  위은조의 블로그입니다.
baseurl: ""
url: "https://notes.pgonee.io"
github_username: pgonee

remote_theme: pgonee
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - .idea/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


author: pgonee
permalink: /:slug

favicon: "logo.png"

theme_config:
  appearance: "auto"
  back_home_text: "뒤로"
  date_format: "%Y-%m-%d"
  show_description: true

sass:
  style: :compressed
